// <auto-generated />
using GamingCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCorner.Data.Migrations
{
    [DbContext(typeof(GamingCornerContext))]
    [Migration("20240827172843_migration27_08_2")]
    partial class migration27_08_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Admin = true,
                            Email = "diego@gmail.com",
                            ImageURL = "",
                            Name = "Diego",
                            Password = "12345",
                            PhoneNumber = "601112734"
                        },
                        new
                        {
                            UserId = 2,
                            Admin = true,
                            Email = "ivan@gmail.com",
                            ImageURL = "",
                            Name = "Ivan",
                            Password = "12345",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            UserId = 3,
                            Admin = false,
                            Email = "adrian@gmail.com",
                            ImageURL = "",
                            Name = "Adrian",
                            Password = "00000",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Property<int>("VideogameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideogameId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pegi")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("VideogameId");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            VideogameId = 1,
                            Available = true,
                            Description = "Altos carros voladores",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co5w0w.webp",
                            Name = "Rocket League",
                            Pegi = 12,
                            Price = 15m,
                            Stock = 3
                        },
                        new
                        {
                            VideogameId = 2,
                            Available = true,
                            Description = "Gran Robo de Autos",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1twh.webp",
                            Name = "GTA 5",
                            Pegi = 18,
                            Price = 13m,
                            Stock = 7
                        },
                        new
                        {
                            VideogameId = 3,
                            Available = true,
                            Description = "Aventura épica en un mundo de fantasía",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lgo.webp",
                            Name = "The Witcher 3",
                            Pegi = 18,
                            Price = 20m,
                            Stock = 5
                        },
                        new
                        {
                            VideogameId = 4,
                            Available = true,
                            Description = "Juego de construcción y aventuras",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2b4k.webp",
                            Name = "Minecraft",
                            Pegi = 7,
                            Price = 25m,
                            Stock = 10
                        },
                        new
                        {
                            VideogameId = 5,
                            Available = true,
                            Description = "Juego de supervivencia y construcción",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ekt.webp",
                            Name = "Fortnite",
                            Pegi = 12,
                            Price = 0m,
                            Stock = 8
                        },
                        new
                        {
                            VideogameId = 6,
                            Available = true,
                            Description = "Juego de disparos en equipo",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co7v86.webp",
                            Name = "Overwatch",
                            Pegi = 12,
                            Price = 30m,
                            Stock = 6
                        },
                        new
                        {
                            VideogameId = 7,
                            Available = true,
                            Description = "Simulación de fútbol",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wm2.webp",
                            Name = "FIFA 21",
                            Pegi = 3,
                            Price = 50m,
                            Stock = 12
                        },
                        new
                        {
                            VideogameId = 8,
                            Available = true,
                            Description = "Aventura en un mundo futurista",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co64re.webp",
                            Name = "Cyberpunk 2077",
                            Pegi = 18,
                            Price = 60m,
                            Stock = 4
                        },
                        new
                        {
                            VideogameId = 9,
                            Available = true,
                            Description = "Aventura en el Viejo Oeste",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.webp",
                            Name = "Red Dead Redemption 2",
                            Pegi = 18,
                            Price = 40m,
                            Stock = 9
                        },
                        new
                        {
                            VideogameId = 10,
                            Available = true,
                            Description = "Aventura de vikingos",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rrw.webp",
                            Name = "Assassin's Creed Valhalla",
                            Pegi = 18,
                            Price = 55m,
                            Stock = 7
                        },
                        new
                        {
                            VideogameId = 11,
                            Available = true,
                            Description = "Juego de disparos en primera persona",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rsg.webp",
                            Name = "Call of Duty: Modern Warfare",
                            Pegi = 18,
                            Price = 50m,
                            Stock = 11
                        },
                        new
                        {
                            VideogameId = 12,
                            Available = true,
                            Description = "Aventura en un mundo postapocalíptico",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.webp",
                            Name = "Horizon Zero Dawn",
                            Pegi = 16,
                            Price = 35m,
                            Stock = 5
                        },
                        new
                        {
                            VideogameId = 13,
                            Available = true,
                            Description = "Simulación de granja",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.webp",
                            Name = "Stardew Valley",
                            Pegi = 7,
                            Price = 20m,
                            Stock = 8
                        },
                        new
                        {
                            VideogameId = 14,
                            Available = true,
                            Description = "Juego de deducción social",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co6kqt.webp",
                            Name = "Among Us",
                            Pegi = 10,
                            Price = 5m,
                            Stock = 15
                        },
                        new
                        {
                            VideogameId = 15,
                            Available = true,
                            Description = "Aventura en el mundo de Hyrule",
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_small/co4n26.png",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Pegi = 12,
                            Price = 60m,
                            Stock = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
